### ISSUE TITLE
casualproxy

### ISSUE THREAD

**Issue by yooniks** [iUnixPL/XProxy-ru#1]
If you are such high-skill programmer, tell me please.. Why can I see a lot of casualproxy's code here?

**Comment by DEVELPL** [comment]
> If you are such high-skill programmer, tell me please.. Why can I see a lot of casualproxy's code here?

Chuj ci do tego typie.. XDDD

**Comment by iUnixPL** [comment]
Dobra yoonkis nie udawaj angola

**Comment by 0100019393332222345566655** [comment]
yooniks anglik XD
